### PR TITLE
fix:use env file to import constants variables

### PR DESCRIPTION
**Pull request by cmcWebCode40**
- Used .env file to import constants variables
#3

### CODE REVIEW

**Comment by nick-verida** [comment]
The app name here doesn't update:
image

It seems to be hard coded here:

```
  <vda-login
    :onError="onError"
    :onSuccess="onSuccess"
    :contextName="contextName"
    :logo="logo"
    loginText="Verida Vue Starter Kit"
  />
```

**Review by nick-verida — CHANGES_REQUESTED** [review]
Need to update this so it isn't hard coded:
```
  <vda-login
    :onError="onError"
    :onSuccess="onSuccess"
    :contextName="contextName"
    :logo="logo"
    loginText="Verida Vue Starter Kit"
  />
```

**Comment by cmcWebCode40** [comment]
@nick-verida , i have made all  requested changes

**Review by nick-verida — APPROVED** [review]
Looks good, merging

**Pull request merged**
